[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.venv", "tesseract", "tesseract4", "cmake"]

[phases.install]
cmds = ["python -m venv /opt/venv", "source /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "source /opt/venv/bin/activate && gunicorn app:app"