[phases.setup]
aptPkgs = [
  "build-essential", 
  "python3-dev", 
  "python3-pip", 
  "tesseract-ocr", 
  "libtesseract-dev", 
  "libpq-dev"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip", 
  "pip install --prefer-binary -r requirements.txt",
  "python -m spacy download en_core_web_sm"
]

[start]
cmd = "gunicorn app:app --bind=0.0.0.0:$PORT"
