[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[environments]